##### ## ####
# Battlegrounds Configurations
# Made by ImpladeDeveloped
# Version: BG-1.2
##### ## ####
---

##### ## ####
# Language
##### ## ####
## Available Languages:
## 1. English
## 2. Malay
## 3. Tagalog
##### ## ####
Language: "English"

##### ## ####
# Prefix
##### ## ####
Prefix: "&9[&cBG&9] "

##### ## ####
# Waiting Lobby In-Game World Location
##### ## ####
lobby:
    x: 1
    y: 1
    z: 1
    world: world
